# Python Essentials

This notebook intends to cover the essentials Pythonic skills needed to for an introductory course in Data Science. If you have zero coding experience I highly recommend to first study [Python 4 Everybody](https://www.py4e.com/). **Optional**: If you already know how to code and want some advance stuffs, [Problem Solving with Algorithms and Data Structures using Python](https://runestone.academy/runestone/books/published/pythonds3/index.html). Both books are **FREE**.

### Lesson
* Variables
* Mathematical Expressions
* Lists
* Tuples
* Sets
* Dictionary
* Python Built-in Functions
* Conditional statements
* Creating your own functions
* Numpy

### Variables

In [1]:
variable = 'cuny'

In [2]:
variable

'cuny'

In [3]:
type(variable)

str

In [4]:
new_variable = 'tech'

In [5]:
new_variable

'tech'

In [6]:
variable = new_variable

In [7]:
variable

'tech'

In [8]:
len(variable)

4

In [9]:
variable[0]

't'

In [10]:
variable[-1]

'h'

In [11]:
variable = 12

In [12]:
variable

12

In [13]:
type(variable)

int

In [14]:
variable = 12.83

In [15]:
type(variable)

float

### Mathematical Expressions

In [16]:
new_variable = 83

In [23]:
variable = 12

In [24]:
new_variable + variable

95

In [25]:
new_variable - variable

71

In [26]:
new_variable * variable

996

In [30]:
new_variable ** variable

106890007738661124410161

In [31]:
new_variable **(1/2)

9.1104335791443

In [27]:
new_variable / variable

6.916666666666667

In [28]:
new_variable // variable

6

In [29]:
new_variable % variable

11

In [32]:
new_variable %2

1

In [33]:
variable %2

0

### List

In [40]:
new_list = ['cuny', 'tech', 'prep', 'fall', 2020]

In [41]:
len(new_list)

5

In [67]:
type(new_list)

list

In [42]:
new_list[0]

'cuny'

In [43]:
new_list[-1]

2020

In [44]:
new_list[1:4]

['tech', 'prep', 'fall']

In [45]:
new_list.append('Science')

In [46]:
new_list

['cuny', 'tech', 'prep', 'fall', 2020, 'Science']

In [48]:
new_list.insert(5, 'Data')

In [49]:
new_list

['cuny', 'tech', 'prep', 'fall', 2020, 'Data', 'Science']

In [50]:
new_list.index('prep')

2

In [51]:
new_list.pop()

'Science'

In [52]:
new_list

['cuny', 'tech', 'prep', 'fall', 2020, 'Data']

In [53]:
new_list.remove('tech')

In [55]:
new_list

['cuny', 'prep', 'fall', 2020, 'Data']

In [56]:
new_list.pop(1)

'prep'

In [57]:
new_list

['cuny', 'fall', 2020, 'Data']

In [58]:
other_list = ['science', 'rocks!!!']

In [59]:
new_list + other_list

['cuny', 'fall', 2020, 'Data', 'science', 'rocks!!!']

In [63]:
new_list[-2] = str(new_list[-2])

In [64]:
new_list

['cuny', 'fall', '2020', 'Data']

In [65]:
' '.join(new_list + other_list)

'cuny fall 2020 Data science rocks!!!'

### Tuples

In [66]:
new_tuple = ('Data', 2020)

In [68]:
len(new_tuple)

2

In [69]:
type(new_tuple)

tuple

In [70]:
new_tuple[0]

'Data'

In [71]:
new_tuple[1]

2020

In [74]:
new_tuple[-2].lower()

'data'

In [73]:
new_tuple[-2] = new_tuple[-2].lower()

TypeError: 'tuple' object does not support item assignment

### Sets

In [76]:
new_set = set()

In [77]:
len(new_set)

0

In [78]:
type(new_set)

set

In [79]:
new_set.add(1)

In [80]:
new_set

{1}

In [81]:
new_set.add(2)
new_set.add(3)

In [84]:
new_set.add('Data')

In [85]:
new_set

{1, 2, 3, 'Data'}

In [86]:
new_set.add(2)

In [87]:
new_set

{1, 2, 3, 'Data'}

In [88]:
new_set.pop()

1

In [89]:
new_set

{2, 3, 'Data'}

### Dictionary

In [90]:
new_dict = {}

In [91]:
new_dict['cuny'] = 'tech'
new_dict['fall'] = 2020

In [92]:
new_dict

{'cuny': 'tech', 'fall': 2020}

In [93]:
new_dict['cuny'] = 'tech prep'

In [94]:
new_dict

{'cuny': 'tech prep', 'fall': 2020}

### Python Built-In Functions

In [95]:
help(new_dict)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self, /, *args, **kwarg

In [96]:
new_list = [1, 5, 9, 12, 3, 4, 8, 5, 2, 4]

In [97]:
sum(new_list)

53

In [98]:
max(new_list)

12

In [99]:
min(new_list)

1

In [105]:
new_int = 12.54381

In [106]:
round(new_int)

13

In [107]:
round(new_int, 1)

12.5

In [109]:
round(new_int, 2), round(new_int, 4)

(12.54, 12.5438)

In [111]:
print(new_list[0])

1


In [112]:
new_list[:3]

[1, 5, 9]

### Conditional Statements

In [113]:
for i in new_list[:3]:
    print(i)

1
5
9


In [114]:
for i in new_list:
    
    if i%2 == 0:
        print('{} is even'.format(i))
    else:
        print('{} is odd'.format(i))

1 is odd
5 is odd
9 is odd
12 is even
3 is odd
4 is even
8 is even
5 is odd
2 is even
4 is even


In [115]:
new_list = [str(i) for i in new_list]

In [116]:
new_list

['1', '5', '9', '12', '3', '4', '8', '5', '2', '4']

In [117]:
new_list = [int(i) for i in new_list]

In [118]:
new_list

[1, 5, 9, 12, 3, 4, 8, 5, 2, 4]

In [119]:
new_list = [i for i in new_list if i%2 == 0]

In [120]:
new_list

[12, 4, 8, 2, 4]

In [127]:
other_list = [i for i in range(10)]

In [128]:
other_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [129]:
other_list = [i+3 for i in other_list]

In [130]:
other_list

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

### Creating Functions

In [131]:
def get_mean(new_list):
    return sum(new_list)/len(new_list)

In [132]:
get_mean(other_list)

7.5

In [135]:
7%2, 6%2

(1, 0)

In [137]:
7//2, 6//2

(3, 3)

In [138]:
def get_median(new_list):
    
    mid = len(new_list)//2
    
    if len(new_list)%2 == 0:
        return (sorted(new_list)[mid] + sorted(new_list)[mid-1])/2
    else:
        return sorted(new_list)[mid]
    

In [139]:
get_median(other_list)

7.5

### Numpy

In [140]:
import numpy as np

In [141]:
array = np.arange(10)

In [142]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
array**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [144]:
array+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [147]:
array.sum()

45

In [148]:
array.max()

9

In [149]:
array.min()

0

In [150]:
array.mean()

4.5

In [154]:
array.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [156]:
array[1:].cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [157]:
array.var()

8.25

In [158]:
array.std()

2.8722813232690143